"""create_cash_registers_and_movements_tables

Revision ID: 07d8d422245c
Revises: e9f0f1e4735d
Create Date: 2026-09-25 17:20:43.018876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07d8d422245c'
down_revision: Union[str, None] = 'e9f0f1e4735d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_registers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('initial_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('current_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('final_declared_balance', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('difference_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', name='cashregisterstatus', native_enum=False), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_registers_company_id'), 'cash_registers', ['company_id'], unique=False)
    op.create_index(op.f('ix_cash_registers_status'), 'cash_registers', ['status'], unique=False)
    op.create_index(op.f('ix_cash_registers_tenant_id'), 'cash_registers', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_cash_registers_user_id'), 'cash_registers', ['user_id'], unique=False)
    op.create_table('cash_movements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cash_register_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('movement_type', sa.Enum('OPENING', 'SUPPLY', 'BLEED', 'CLOSING', 'SALE', name='cashmovementtype', native_enum=False), nullable=False),
    sa.Column('payment_method', sa.Enum('MONEY', 'PIX', 'CREDIT_CARD', 'DEBIT_CARD', 'BOLETO', 'OTHER', name='paymentmethod', native_enum=False), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cash_register_id'], ['cash_registers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_movements_cash_register_id'), 'cash_movements', ['cash_register_id'], unique=False)
    op.create_index(op.f('ix_cash_movements_company_id'), 'cash_movements', ['company_id'], unique=False)
    op.create_index(op.f('ix_cash_movements_movement_type'), 'cash_movements', ['movement_type'], unique=False)
    op.create_index(op.f('ix_cash_movements_tenant_id'), 'cash_movements', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_cash_movements_user_id'), 'cash_movements', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cash_movements_user_id'), table_name='cash_movements')
    op.drop_index(op.f('ix_cash_movements_tenant_id'), table_name='cash_movements')
    op.drop_index(op.f('ix_cash_movements_movement_type'), table_name='cash_movements')
    op.drop_index(op.f('ix_cash_movements_company_id'), table_name='cash_movements')
    op.drop_index(op.f('ix_cash_movements_cash_register_id'), table_name='cash_movements')
    op.drop_table('cash_movements')
    op.drop_index(op.f('ix_cash_registers_user_id'), table_name='cash_registers')
    op.drop_index(op.f('ix_cash_registers_tenant_id'), table_name='cash_registers')
    op.drop_index(op.f('ix_cash_registers_status'), table_name='cash_registers')
    op.drop_index(op.f('ix_cash_registers_company_id'), table_name='cash_registers')
    op.drop_table('cash_registers')
    # ### end Alembic commands ###
